### PR TITLE
FLOE-583: Update the UI Options page

### PR DESCRIPTION
**Pull request by jobara**
https://issues.fluidproject.org/browse/FLOE-583

I've made a pass at updating the copy of the UI Options page. I haven't added in images or other things that may require extra styling work because I'm finding it difficult to maintain consistency with the rest of the site styling using the foundation framework included. This is partially because unclear if it is a subset of foundation 6 that is missing parts or if I'm just not locating the correct docs for the version we're using. 

I'm thinking that we can either update this page further with the site redesign, or I could take a stab a modernizing the CSS for the entire site at this time as well. I'd lean towards the former as we are in the midst of migrating this site to a SSG in a GSoC project this year.

### CODE REVIEW

**Comment by Ayush23Dash** [comment]
@jobara  should this be considered by me as a contributor during the GSoC period?

**Comment by jobara** [comment]
@Ayush23Dash sorry, I'm not really sure what your question means.

**Comment by Ayush23Dash** [comment]
@jobara I mean, can I make all the changes required for https://issues.fluidproject.org/browse/FLOE-583 The changes include the images to be added , the styling changes to be made and all the other changes mentioned in the given link.
So I am asking can you count me in for this?

**Comment by jhung** [comment]
@jobara I wonder if this issue can be closed? The UI Options page has since been updated with relevant links (to the Infusion Docs) to getting and using UI Options.

**Comment by jobara** [comment]
@jhung, I'm just going to close it, not sure it adds more over what is there now.

**Pull request closed without merging**
