### PR TITLE
Using cursor as pointer in resource page #147

### PR DESCRIPTION
**Pull request by Shikhar15606**
Fixed Issue Number => #147

### CODE REVIEW

**Comment by Shikhar15606** [comment]
before : 
before
after :
after

**Comment by Shikhar15606** [comment]
Before 
b
After
a

**Comment by Shikhar15606** [comment]
Issue Number => #147 
link => [https://github.com/fluid-project/floeproject.org/issues/147](url)

**Review by Raunaksingh100 — COMMENTED** [review]
hey, plz update your branch because this branch has conflicts

**Comment by greatislander** [comment]
We've decided not to make the changes proposed in #147 but thanks for your contribution.

**Pull request closed without merging**
