### PR TITLE
#176 fixed

### PR DESCRIPTION
**Pull request by Raunaksingh100**
### descriptions
fixed the images to centre from right in all types of devices (bug fixed)

And also fixed the text which is overlapping to images when we set text size to 0.5 in desktop as well as in mobile view

### issue
#176  and #178 

### preview link-
https://trusting-swanson-0ef044.netlify.app/ 

### screenshot issue FIXED -
rk

### CODE REVIEW

**Comment by Raunaksingh100** [comment]
@jhung @colinbdclark you can check my code change through this link  https://trusting-swanson-0ef044.netlify.app/

i fixed this bug in all types of devices 
thanks i hope you like it

**Comment by colinbdclark** [comment]
Thanks for your contributions, @Raunaksingh100. I've left comments on the issue you filed, #176, regarding this. At the moment, we're not accepting pull requests for styling issues while the site is being partially redesigned and ported to a static site generator.

For future pull requests, please also ensure that you're following the commit message [guidelines](https://wiki.fluidproject.org/display/fluid/Coding+and+Commit+Standards) for our community, which you can find in the wiki. For example, "Fixed" isn't a very informative commit message when someone is looking back at the history of the code later.

**Comment by Raunaksingh100** [comment]
@colinbdclark sure

**Comment by Raunaksingh100** [comment]
with the same code the two issues  fixed you can test with any screen or can decrease the text size no bug plz merge this pr 
you can test the two issues from the this link -------- https://trusting-swanson-0ef044.netlify.app/
@colinbdclark  thanks

**Pull request closed without merging**
