### PR TITLE
Home Key added and is working fine.

### PR DESCRIPTION
**Pull request by shash137**
Issue number #154 solved.

### CODE REVIEW

**Comment by Ayush23Dash** [comment]
@shash137 the home key is not necessary to be added,as the floe logo itself works as the home button on any specified page.More importantly, for a visitor of the website, it is more obvious to click on the logo of the website to go to the home page.
Hope you get it 👍

**Comment by shash137** [comment]
@Ayush23Dash I agree with your point but as of now logo is clickable and is linking to home page, but how will new person will understand, because it neither looks like a button on hover over a logo, neither it changes it's color like in [fluid](https://fluidproject.org/index.html) and there is a home button as well in the fluid project website. I think either of the two thing is possible or both i.e. make logo look more like clickable by changing the color or by adding the home button or do both like in fluid project. 
Rest everything is on mentors of the project. 
Hope you get my point.

**Comment by Ayush23Dash** [comment]
@shash137 I totally understand what you are trying to say,and yes changing color on hover can be a good change,but I believe in today's date it is quite obvious that the logo signifies the home page.
And moreover all of the styling changes will be considered during the GSoC project,as this site requires a migration to a modern SSG.

**Comment by Chaitanyassr** [comment]
@shash137 @Ayush23Dash  Adding a home button or making logo work as home button is actually depends upon the audience you  are dealing with. although its quite obvious nowdays that logo will work as the home button but less tech savvy group might get confused. that is the reason why **facebook** has home button as well as logo as home button. 
but sometimes its quite misleading adding a home button as user think that its not the home page at which they are currently in. But that also considering the UX its better to  add a home page with minor tweeks like **underlying the home button when you are at the home page**.
- more example - codelearncreate site 
Screenshot (233)
Fluid project website - 
Screenshot (234)

**Comment by shash137** [comment]
@Chaitanyassr Thanks you got my point that's what I was thinking and I made a PR for the Home tab, but then I realized that to make UI better by changing color on hover over logo, will do directly in GSoC because now mentors will not merge as this project will be migrated.

**Comment by Chaitanyassr** [comment]
> @Chaitanyassr Thanks you got my point that's what I was thinking and I made a PR for the Home tab, but then I realized that to make UI better by changing color on hover over logo, will do directly in GSoC because now mentors will not merge as this project will be migrated.

ahan! One can do that ..although fixes to the User Experience (UX) are not a priority, as the site may be redesign by us in the future.

**Comment by Ayush23Dash** [comment]
@Chaitanyassr yes I think for the less tech savvy group, it might help.Actually I was somewhat confused that why these websites have the home button, however after reading your comment I think that this is necessary. Or maybe how @shash137 mentioned, it could be implemented similar to the fluid website as well.But yes at the end it depends upon the mentors' choice on this.
Thanks both of you for this healthy discussion.

**Comment by Chaitanyassr** [comment]
> @Chaitanyassr yes I think for the less tech savvy group, it might help.Actually I was somewhat confused that why these websites have the home button, however after reading your comment I think that this is necessary. Or maybe how @shash137 mentioned, it could be implemented similar to the fluid website as well.But yes at the end it depends upon the mentors' choice on this.
> Thanks both of you for this healthy discussion.

No worries, and thank you to you too and @shash137 :)

**Comment by shash137** [comment]
Thank you guys!! it was a good discussion. @Chaitanyassr and @Ayush23Dash

**Comment by greatislander** [comment]
Thanks, all— we will explore this option in our redesign but will address this in a separate PR.

**Pull request closed without merging**
