### PR TITLE
adding margin to footer. Issue #172

### PR DESCRIPTION
**Pull request by himanshujaidka**
Screenshot (27)
make a block and footer distinguishable by adding margin

### CODE REVIEW

**Comment by himanshujaidka** [comment]
before
See that there is no space between the gray block and footer and it's not sounds good

**Comment by himanshujaidka** [comment]
after
After adding margin it looks goods

**Comment by jobara** [comment]
@himanshujaidka thanks for updating about the issue. I think the lack of margin is intentional in the design and not a bug. That being said this site will be redesigned so changes such as this are not priority at the moment.

**Comment by himanshujaidka** [comment]
okay no problem but until the new website launches, we have to give some priority to the existing one, it's just my opinion

**Comment by colinbdclark** [comment]
Hi @himanshujaidka, thanks for your contribution. We're not accepting unsolicited changes to the site's design at this point. If you'd like to contribute to our projects, please read carefully our [Getting Involved](https://wiki.fluidproject.org/display/fluid/Get+Involved) page, and if your interest is related to Google Summer of Code, also our [Google Summer of Code](https://wiki.fluidproject.org/display/fluid/Google+Summer+of+Code+2020+with+the+Fluid+Project) information page as well as Google's own [GSoC Student Guide](https://google.github.io/gsocguides/student/). The best way to contribute is to take the time to find issues that are important to the community and substantive, but within your skill set. This typically involves taking time to learn about our projects and community, read the source code, and understand our priorities and goals prior to submitting pull requests.

**Pull request closed without merging**
