### PR TITLE
Update this docs

### PR DESCRIPTION
**Pull request by khushishikhu**
updated type setting links. issue no. #98

### CODE REVIEW

**Comment by khushishikhu** [comment]
@jobara  sir please review it

**Comment by sachin10101998** [comment]
duplicate of #99

**Comment by sachin10101998** [comment]
@khushishikhu there's already a pending PR #99  for the same issue by @ashimgarg who reported this issue. We are currently in the middle of migrating the site to a new static site generator and will be making a few UI changes to the same. So, it's best not to make changes to the current site.

**Comment by khushishikhu** [comment]
@sachin10101998  okay sir, Thank you.

**Pull request closed without merging**
