### PR TITLE
Center the all images in mobile phones

### PR DESCRIPTION
**Pull request by mugymb**
image

### CODE REVIEW

**Comment by mugymb** [comment]
@jhung check it plz

**Comment by jobara** [comment]
@mugymb is this a fix for a specific issue? If so please indicate which issue it resolves so that they are linked together.

**Comment by mugymb** [comment]
@jobara i solved issue #107 and #116

**Comment by jobara** [comment]
@mugymb please see https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Pull request closed without merging**
