### PR TITLE
FLOE-580: fixed nav bar items splitting for small screen devices

### LINKED ISSUE #106: at text size 1.1 and greater option in "ui option" went down to News make it look like news option.
## Describe the bug
at text size 1.1 and greater option in "ui option" went down to News make it look like news option.

### To reproduce
1.click on preference
2. text size set to 1.1 or greater
3. See error

### Expected behavior
option should be below ui so that it can feel sensible while reading.

## Screenshots
Screenshot (165)

 - Browser [e.g. chrome]

### LINKED ISSUE #123: "UI Options" of navigation bar splits into UI and Options in mobile devices.
## Describe the bug
"UI Options" of navigation bar splits into UI and Options in mobile devices making it look like News Options.

### To reproduce
1. Go to floeproject.org on iPhone 5/SE
2. See error

## Screenshots
Screenshot from 2020-03-02 07-08-17

### Expected behavior
UI Options should not split and should move together if a new line is to be used to display the whole of navbar items.
Screenshot from 2020-03-02 07-12-29

### Desktop
 - OS: Ubuntu 18.04
 - Browser : Chrome
 - Version: Version 80.0.3987.122 (Official Build) (64-bit)

## Additional context or notes
The links overlapped when the UI Options link goes into the next line as shown.
The overlapping UI Options and News link, when hovered over, is solved by adding a margin to links.
Screenshot from 2020-03-02 07-20-39

### PR DESCRIPTION
**Pull request by sachin10101998**
fixes #123 
Added margin-top and display properties so as to avoid overlapping of "UI Options" link with the "News" link as described in #123 (Additional content column). 
Simultaneously fixes #106

### CODE REVIEW

**Comment by aashimgarg** [comment]
This does not solve the purpose as now also on resizing the window for small devices the ui options is coming down.

**Comment by sachin10101998** [comment]
@aashimgarg the goal of #123 was to make sure that the word 'UI' and 'Options' stay together on resizing. When they split, the 'News' link looks like 'News Options'.
Keeping the navbar items in a single line is totally different issue from this.

**Comment by aashimgarg** [comment]
@sachin10101998 now the link looks like "news Ui options" . So what is the point in doing that.

**Comment by sachin10101998** [comment]
@aashimgarg please go through #123. The goal of this PR was to make sure that "UI" and  "Options" stay together since they are together. 
**Keeping nav bar items in a single line is a separate issue**

**Comment by sachin10101998** [comment]
Refers to old version of the site. Hence closing the PR but the issue still stands at #123

**Pull request closed without merging**
